name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin' # Adotei a distribuição mais recente conhecida como 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: mattsandes12
          password: !docker:learn12

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin' # Adotei a distribuição mais recente conhecida como 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Deploy to production
        run: |
          docker tag mattsandes12/myapi-with-docker:latest mattsandes12/myapi-with-docker:${{ github.run_id }}
          docker push mattsandes12/myapi-with-docker:${{ github.run_id }}
          docker push mattsandes12/myapi-with-docker:latest
